---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
framework_version: latest
serverless_language: ''
polling_url: "{{ api_url }}?agency={{ agency }}&route={{ route }}"
polling_headers: Authorization=Bearer {{ api_key }}
polling_body: ''
id: 310138
custom_fields:
- keyname: author_bio
  name: About This Plugin
  field_type: author_bio
  description: "Shows live arrival times for any Swiftly-powered transit agency and route. This plugin is self-hosted: you must deploy your own proxy (Github provides Cloudflare Worker example) and provide your own Swiftly API key before it can pull data. See the GitHub repo for setup instructions."
  category: travel,life
  email_address: nickzelei+trmnl@gmail.com
  github_url: https://github.com/nickzelei/swiftly-route-trmnl
- keyname: api_url
  field_type: string
  name: Proxy API Url
  description: The API base url used to hit the proxy server that returns the expected Swiftly response.
  placeholder: https://example.com
  group: "Proxy Connection"
- keyname: api_key
  field_type: string
  name: Proxy API Key
  description: The API key used to authenticate with your Swiftly proxy (not the API key provided by Swiftly!)
  group: "Proxy Connection"
- keyname: agency
  field_type: string
  placeholder: sfbay-ferry
  name: Agency
  description: The agency key provided to you by Swiftly
  group: "Route"
- keyname: route
  field_type: number
  placeholder: 19417
  name: Route
  description: The route key that you wish to poll
  group: "Route"
name: Swiftly
refresh_interval: 15
