---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
framework_version: latest
serverless_language: ''
polling_url: "{{ api_url }}?agency={{ agency }}&route={{ route }}"
polling_headers: Authorization=Bearer {{ api_key }}
polling_body: ''
id: 310138
custom_fields:
- keyname: api_url
  field_type: string
  name: Proxy API Url
  description: The API base url used to hit the proxy server that returns the expected Swiftly response.
  placeholder: https://example.com
- keyname: agency
  field_type: string
  placeholder: sfbay-ferry
  name: Agency
  description: The agency key provided to you by Swiftly
- keyname: route
  field_type: number
  placeholder: 19417
  name: Route
  description: The route key that you wish to poll
- keyname: api_key
  field_type: string
  name: Proxy API Key
  description: The API key used to authenticate with your Swiftly proxy (not the API key provided by Swiftly!)
name: Swiftly
refresh_interval: 15
